Downloads/FinalProject-1.1.0/FinalProject-1.0.0/Controllers/LeaveRequestController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HR_App.Models;
using HR_App.Data;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Text;
using Microsoft.AspNetCore.Authorization;

namespace HR_App.Controllers
{
    public class LeaveRequestController : Controller
    {
        private AppDbContext _appdbcontext;
        private readonly ILogger<LeaveRequestController> _logger;

        public LeaveRequestController(ILogger<LeaveRequestController> logger, AppDbContext appDbContext)
        {
            _logger = logger;
            _appdbcontext = appDbContext;
        }
        
        [Authorize]
        public IActionResult Index(string search, int _crntpage=1)
        {
            ViewBag.search = search;
            var j = (from i in _appdbcontext.pagings select i).FirstOrDefault();
            if (j == null)
            {
                Paging paging = new Paging()
                {
                    CurrentPage = 1
                };
                _appdbcontext.pagings.Add(paging);
                _appdbcontext.SaveChanges();
                var y = (from i in _appdbcontext.leaves where i.status == "submitted" select i).Count();
            ViewBag.count = y;
            var z = _appdbcontext.pagings.Find(1);
            z.CurrentPage = _crntpage;
            _appdbcontext.SaveChanges();
            if (z.CurrentPage == 1)
            {
                if (search != null)
                {
                    var take = z.ShowItem;
                    var x = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.name.Contains(search) || i.position.Contains(search) || i.department.Contains(search) || i.status.Contains(search) && i.status=="submitted") select i;
                    var k = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.name.Contains(search) || i.position.Contains(search) || i.department.Contains(search) || i.status.Contains(search) && i.status=="allowed") select i;
                    var l = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.name.Contains(search) || i.position.Contains(search) || i.department.Contains(search) || i.status.Contains(search) && i.status=="rejected") select i;
                    var get = from a in x.Take(take) select a;
                    var get1 = from a in k.Take(take) select a;
                    var get2 = from a in l.Take(take) select a;
                    ViewBag.emp = get;
                    ViewBag.emp1 = get1;
                    ViewBag.emp2 = get2;
                    ViewBag.page = z;
                    return View();
                }
                else
                {
                    var take = z.ShowItem;
                    var x = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.status == "submitted") select i;
                    var k = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.status == "allowed") select i;
                    var l = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.status == "rejected") select i;
                    var get = from a in x.Take(take) select a;
                    var get1 = from a in k.Take(take) select a;
                    var get2 = from a in l.Take(take) select a;
                    ViewBag.emp = get;
                    ViewBag.emp1 = get1;
                    ViewBag.emp2 = get2;
                    ViewBag.page = z;
                    return View();
                }
            }
            else
            {
                if (search != null)
                {
                    var take = z.ShowItem;
                    var x = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.name.Contains(search) || i.position.Contains(search) || i.department.Contains(search) || i.status.Contains(search) && i.status=="submitted") select i;
                    var k = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.name.Contains(search) || i.position.Contains(search) || i.department.Contains(search) || i.status.Contains(search) && i.status=="allowed") select i;
                    var l = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.name.Contains(search) || i.position.Contains(search) || i.department.Contains(search) || i.status.Contains(search) && i.status=="rejected") select i;
                    var get = from a in x.Skip(take*(z.CurrentPage-1)).Take(take) select a;
                    var get1 = from a in k.Skip(take*(z.CurrentPage-1)).Take(take) select a;
                    var get2 = from a in l.Skip(take*(z.CurrentPage-1)).Take(take) select a;
                    ViewBag.emp = get;
                    ViewBag.emp1 = get1;
                    ViewBag.emp2 = get2;
                    ViewBag.page = z;
                    return View();
                }
                else
                {
                    var take = z.ShowItem;
                    var x = (from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.status == "submitted") select i).Skip(take*(z.CurrentPage-1)).Take(take);
                    var k = (from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.status == "allowed") select i).Skip(take*(z.CurrentPage-1)).Take(take);
                    var l = (from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.status == "rejected") select i).Skip(take*(z.CurrentPage-1)).Take(take);
                    ViewBag.emp = x;
                    ViewBag.emp1 = l;
                    ViewBag.emp2 = k;
                    ViewBag.page = z;
                    return View();
                }
            }
            }
            else
            {
                var y = (from i in _appdbcontext.leaves where i.status == "submitted" select i).Count();
            ViewBag.count = y;
            var z = _appdbcontext.pagings.Find(1);
            z.CurrentPage = _crntpage;
            _appdbcontext.SaveChanges();
            if (z.CurrentPage == 1)
            {
                if (search != null)
                {
                    var take = z.ShowItem;
                    var x = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.name.Contains(search) || i.position.Contains(search) || i.department.Contains(search) || i.status.Contains(search) && i.status=="submitted") select i;
                    var k = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.name.Contains(search) || i.position.Contains(search) || i.department.Contains(search) || i.status.Contains(search) && i.status=="allowed") select i;
                    var l = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.name.Contains(search) || i.position.Contains(search) || i.department.Contains(search) || i.status.Contains(search) && i.status=="rejected") select i;
                    var get = from a in x.Take(take) select a;
                    var get1 = from a in k.Take(take) select a;
                    var get2 = from a in l.Take(take) select a;
                    ViewBag.emp = get;
                    ViewBag.emp1 = get1;
                    ViewBag.emp2 = get2;
                    ViewBag.page = z;
                    return View();
                }
                else
                {
                    var take = z.ShowItem;
                    var x = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.status == "submitted") select i;
                    var k = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.status == "allowed") select i;
                    var l = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.status == "rejected") select i;
                    var get = from a in x.Take(take) select a;
                    var get1 = from a in k.Take(take) select a;
                    var get2 = from a in l.Take(take) select a;
                    ViewBag.emp = get;
                    ViewBag.emp1 = get1;
                    ViewBag.emp2 = get2;
                    ViewBag.page = z;
                    return View();
                }
            }
            else
            {
                if (search != null)
                {
                    var take = z.ShowItem;
                    var x = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.name.Contains(search) || i.position.Contains(search) || i.department.Contains(search) || i.status.Contains(search) && i.status=="submitted") select i;
                    var k = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.name.Contains(search) || i.position.Contains(search) || i.department.Contains(search) || i.status.Contains(search) && i.status=="allowed") select i;
                    var l = from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.name.Contains(search) || i.position.Contains(search) || i.department.Contains(search) || i.status.Contains(search) && i.status=="rejected") select i;
                    var get = from a in x.Skip(take*(z.CurrentPage-1)).Take(take) select a;
                    var get1 = from a in k.Skip(take*(z.CurrentPage-1)).Take(take) select a;
                    var get2 = from a in l.Skip(take*(z.CurrentPage-1)).Take(take) select a;
                    ViewBag.emp = get;
                    ViewBag.emp1 = get1;
                    ViewBag.emp2 = get2;
                    ViewBag.page = z;
                    return View();
                }
                else
                {
                    var take = z.ShowItem;
                    var x = (from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.status == "submitted") select i).Skip(take*(z.CurrentPage-1)).Take(take);
                    var k = (from i in _appdbcontext.leaves.OrderBy(a => a.outtime) where (i.status == "allowed") select i).Skip(take*(z.CurrentPage-1)).Take(take);

Downloads/FinalProject-1.1.0/FinalProject-1.0.0/Views/LeaveRequest/Add.cshtml
<style>
  .upload-btn-wrapper {
  position: relative;
  overflow: hidden;
  display: inline-block;
}

.btnx {
  border: 2px solid gray;
  color: gray;
  background-color: white;
  padding: 8px 20px;
  border-radius: 8px;
  font-size: 10px;
  font-weight: bold;
}

.upload-btn-wrapper input[type=file] {
  font-size: 20px;
  position: absolute;
  left: 0;
  top: 0;
  opacity: 0;
}
</style>

<!DOCTYPE html>
<html>
<title></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="text-center">
        <h2><b>Employee Leave Form</b></h2>
        <p>Be Careful with Sensitive Data Information and Privacy</p>
      </div>
    </div>
  </div>
</div>
<br>

<div class="w3-sidebar w3-bar-block w3-black w3-card" style="width:130px; height: 275px">
  <h5 class="w3-bar-item">Biodata</h5>
  <button class="w3-bar-item w3-button tablink" onclick="openLink(event, 'Fade')">Form</button>
</div>

<form method="POST" enctype="multipart/form-data">
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-6">
    <button asp-action="Added" asp-controller="LeaveRequest" class="btn btn-success">Send</button>
    <button type="button" class="btn btn-primary" onclick="window.location.href ='/LeaveRequest'">Cancel</button>
    </div>
  </div>
</div>
<br>
<br>

<div style="margin-left:170px">
  <div class="w3-padding"><b>Fill this form completely and correct</b></div>

  <div id="Fade" class="w3-container city w3-animate-left" style="display:none">
    <h2>Form</h2>
    <div class="row">
      <div class="col">
        <label>Full Name</label>
        <input class="form-control" placeholder="Name" id="name" name="name" required>
      </div>
      <div class="col">
        <label>Position</label>
        <input class="form-control" placeholder="Position" id="position" name="position" required>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col">
        <label>Department</label>
        <input class="form-control" placeholder="Department" id="department" name="department" required>
      </div>
    </div>
    <br>

    <div class="row">
      <div class="col">
        <label>Outtime</label>
        <input class="form-control" type="date" placeholder="date" id="outtime" name="outtime" required>
      </div>
      <div class="col">
        <label>Intime</label>
        <input class="form-control" type="date" placeholder="date" id="intime" name="intime" required>
      </div>
  </div>
</div>
<br>
</form>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>

<script>
function openLink(evt, animName) {
  var i, x, tablinks;
  x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < x.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" w3-red", "");
  }
  document.getElementById(animName).style.display = "block";
  evt.currentTarget.className += " w3-red";
}
</script>

@section Scripts
    {
        <script type="text/javascript">
           $(document).ready(function () {
    
            let connection = new signalR.HubConnectionBuilder().withUrl("/chatHub").build();

            connection.start().then(function() {
                console.log("Berhasil");

                $('#leave').on('click', function (event) {
                    let count = $('#count').val();
                    console.log(count);
                    connection.invoke("Send", count)
                        .then(data => {
                            console.log('Berhasil kirim data')
                        }).catch(err => {
                        return console.error(err.toString());
                    })
                });

            }).catch(function (err) {
                return console.error(err.toString());
            });
                })
        </script>
    }

</body>
</html>

Downloads/FinalProject-1.1.0/FinalProject-1.0.0/Views/LeaveRequest/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Arimo:400,700&display=swap">
<style>
body{
  font-family: 'Arimo', sans-serif;
}
h2{
  color:#000;
  text-align:center;
  font-size:2em;
}
.warpper{
  display:flex;
  flex-direction: column;
  align-items: center;
}
.tab{
  cursor: pointer;
  padding:20px 100px;
  margin:0px 10px;
  background:#000;
  display:inline-block;
  color:#fff;
  border-radius:3px 3px 0px 0px;
  box-shadow: 0 0.5rem 0.8rem #00000080;
}
.panels{
  background:#fff;
  box-shadow: 0 2rem 2rem #00000080;
  min-height:375px;
  width:100%;
  max-width:1200px;
  border-radius:3px;
  overflow:hidden;
  padding:20px;  
}
.panel{
  display:none;
  animation: fadein .8s;
}
.panel-title{
  font-size:1.5em;
  font-weight:bold
}
.radio{
  display:none;
}
#one:checked ~ .panels #one-panel,
#two:checked ~ .panels #two-panel,
#three:checked ~ .panels #three-panel{
  display:block
}
#one:checked ~ .tabs #one-tab,
#two:checked ~ .tabs #two-tab,
#three:checked ~ .tabs #three-tab{
  background:#fff;
  color:#000;
  border-top: 3px solid #000;
}

* {box-sizing: border-box}

/* Set height of body and the document to 100% */
body, html {
  height: 100%;
  margin: 0;
  font-family: Arial;
}

/* Style tab links */
.tablink {
  background-color: #555;
  color: white;
  float: left;
  border: none;
  outline: none;
  cursor: pointer;
  padding: 14px 16px;
  font-size: 17px;
  width: 33.33%;
}

.tablink:hover {
  background-color: #777;
}

/* Style the tab content (and add height:100% for full page content) */
.tabcontent {
  color: white;
  display: none;
  padding: 100px 20px;
  height: 100%;
}

#News {background-color: green;}
#Contact {background-color: teal;}
#About {background-color: orange;}
</style>
</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <div class="text-center">
      <h1><b>Leave Request System</b></h1>
      <p>Be Carefuly with Employees Permition</p>
      </div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
      <form method="GET">
        <div class="form-group">
          @{
          var k = ViewBag.search;
          <input class="form-control" id="search" name="search" placeholder="Searching for. . ." value=@k>
          }
          <div class="text-center">
            <br>
          <button asp-action="Index" asp-controller="LeaveRequest" class="btn btn-outline-info">Search</button>
          <button asp-action="ExportId" asp-controller="LeaveRequest" class="btn btn-outline-info">Export</button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>
<br>

<div class="container">
  <div class="row">
    <div class="col-md-8">
        <a href="/LeaveRequest/Add" class="btn btn-info">Add Leave Request</a>
        <a href="/LeaveRequest/Export" class="btn btn-info">Export (All)</a>
    </div>
  </div>
</div>
<br>
<br>

<div class="warpper">
  <input class="radio" id="one" name="group" type="radio" checked>
  <input class="radio" id="two" name="group" type="radio">
  <input class="radio" id="three" name="group" type="radio">
  <div class="tabs">
  <label class="tab" id="one-tab" for="one">Submitted</label>
  <label class="tab" id="two-tab" for="two">Allowed</label>
  <label class="tab" id="three-tab" for="three">Rejected</label>
  </div>
  <div class="panels">
  <div class="panel" id="one-panel">
    <ul class="list-group">
    @{
        var x = ViewBag.emp;
        foreach (var i in x)
        {
            if( i.status == "submitted")
            {
                <li class="list-group-item">
                <div class="container">
                  <div class="row">
                    <div class="col-md-3">
                    Name: @i.name
                    </div>
                    <div class="col-md-5">
                    Outtime: @i.outtime
                    </div>
                    <div class="col-md-3">
                    Intime: @i.intime
                    </div>
                    <div class="col-md-1">
                    <a href='/LeaveRequest/Information/@i.id' class="btn btn-outline-warning">Info</a>
                    </div>
                  </div>
                </div>
                </li>
                <br>
            }
        }
    }
    </ul>
  </div>
  <div class="panel" id="two-panel">
    <ul class="list-group">
    @{
        var y = ViewBag.emp1;
        foreach (var i in y)
        {
            if( i.status == "allowed")
            {
                <li class="list-group-item">
                <div class="container">
                  <div class="row">
                    <div class="col-md-3">
                    Name: @i.name
                    </div>
                    <div class="col-md-5">
                    Outtime: @i.outtime
                    </div>
                    <div class="col-md-3">
                    Intime: @i.intime
                    </div>
                    <div class="col-md-1">
                    <a href='/LeaveRequest/Information/@i.id' class="btn btn-outline-warning">Info</a>
                    </div>
                  </div>
                </div>
                </li>
                <br>
            }
        }
    }
    </ul>
  </div>
  <div class="panel" id="three-panel">
    <ul class="list-group">
    @{
        var z = ViewBag.emp2;
        foreach (var i in z)
        {
            if( i.status == "rejected")
            {
               <li class="list-group-item">
                <div class="container">
                  <div class="row">
                    <div class="col-md-3">
                    Name: @i.name
                    </div>
                    <div class="col-md-5">
                    Outtime: @i.outtime
                    </div>
                    <div class="col-md-3">
                    Intime: @i.intime
                    </div>
                    <div class="col-md-1">
                    <a href='/LeaveRequest/Information/@i.id' class="btn btn-outline-warning">Info</a>
                    </div>
                  </div>
                </div>
                </li>
                <br>
            }
        }
    }
    </ul>
  </div>
  </div>
</div>
<br>
<br>

<div class="container">
<div class="column">
<div class="col-lg-12 col-sm-5">
<nav aria-label="...">
  <ul class="pagination justify-content-center">
    @{
      var paging = ViewBag.page;
    <li class="page-item"><button class="page-link" value="1" id="btn1" onclick="javascript:page1(this)">1</button></li>
    <li class="page-item"><button class="page-link" value="2" id="btn2" onclick="javascript:page2(this)">2</button></li>
    <li class="page-item"><button class="page-link" value="3" id="btn3" onclick="javascript:page3(this)">3</button></li>
    <li class="page-item"><button class="page-link" value="4" id="btn4" onclick="javascript:page4(this)">4</button></li>
    <li class="page-item"><button class="page-link" value="5" id="btn5" onclick="javascript:page5(this)">5</button></li>
    <li class="page-item"><button class="page-link" value="6" id="btn6" onclick="javascript:page6(this)">6</button></li>
    }
  </ul>

</body>
</html>

<script type="text/javascript">
function page1(btn)
{
  var search = document.getElementById("search").value;
  location.href='/LeaveRequest/Index?_crntpage=1&search='+search;
}
function page2(btn)
{
  var search = document.getElementById("search").value;
  location.href='/LeaveRequest/Index?_crntpage=2&search='+search;
}
function page3(btn)
{
  var search = document.getElementById("search").value;
  location.href='/LeaveRequest/Index?_crntpage=3&search='+search;
}
function page4(btn)
{
  var search = document.getElementById("search").value;
  location.href='/LeaveRequest/Index?_crntpage=4&search='+search;
}
function page5(btn)
{
  var search = document.getElementById("search").value;
  location.href='/LeaveRequest/Index?_crntpage=5&search='+search;
}
function page6(btn)
{
  var search = document.getElementById("search").value;
  location.href='/LeaveRequest/Index?_crntpage=6&search='+search;
}
</script>