Downloads/FinalProject-1.1.0/FinalProject-1.0.0/Models/Applicant.cs
using System;

namespace HR_App.Models
{
    public class Applicant
    {
        public Guid id {get; set;}
        public string name { get; set; }
        public string cv { get; set; }
        public string photo { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string gender { get; set; }
        public DateTime bhirtdate { get; set; }
        public string bhirtplace { get; set; }
        public string address { get; set; }
        public string posisi { get; set; }
        public string status { get; set; }
        public DateTime apply { get; set; }
    }
}

Downloads/FinalProject-1.1.0/FinalProject-1.0.0/Controllers/ApplicantController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using HR_App.Models;
using HR_App.Data;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Text;
using Microsoft.AspNetCore.Authorization;

namespace HR_App.Controllers
{
    public class ApplicantController : Controller
    {
        private AppDbContext _appdbcontext;
        private readonly ILogger<ApplicantController> _logger;

        public ApplicantController(ILogger<ApplicantController> logger, AppDbContext appDbContext)
        {
            _logger = logger;
            _appdbcontext = appDbContext;
        }
        
        [Authorize]
        public IActionResult Index(string search, int _crntpage=1)
        {
            ViewBag.search = search;
            var j = (from i in _appdbcontext.pagings select i).FirstOrDefault();
            if (j == null)
            {
                Paging paging = new Paging()
                {
                    CurrentPage = 1
                };
                _appdbcontext.pagings.Add(paging);
                _appdbcontext.SaveChanges();
                var y = (from i in _appdbcontext.leaves where i.status == "submitted" select i).Count();
            ViewBag.count = y;
            var z = _appdbcontext.pagings.Find(1);
            z.CurrentPage = _crntpage;
            _appdbcontext.SaveChanges();
            if (z.CurrentPage == 1)
            {
                if (search != null)
                {
                    var take = z.ShowItem;
                    var x = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.name.Contains(search) || i.status.Contains(search) && i.status=="unprocessed") select i;
                    var k = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.name.Contains(search) || i.status.Contains(search) && i.status=="psychotest") select i;
                    var l = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.name.Contains(search) || i.status.Contains(search) && i.status=="interview") select i;
                    var get = from a in x.Take(take) select a;
                    var get1 = from a in k.Take(take) select a;
                    var get2 = from a in l.Take(take) select a;
                    ViewBag.emp = get;
                    ViewBag.emp1 = get1;
                    ViewBag.emp2 = get2;
                    ViewBag.page = z;
                    return View();
                }
                else
                {
                    var take = z.ShowItem;
                    var x = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.status == "unprocessed") select i;
                    var k = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.status == "psychotest") select i;
                    var l = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.status == "interview") select i;
                    var get = from a in x.Take(take) select a;
                    var get1 = from a in k.Take(take) select a;
                    var get2 = from a in l.Take(take) select a;
                    ViewBag.emp = get;
                    ViewBag.emp1 = get1;
                    ViewBag.emp2 = get2;
                    ViewBag.page = z;
                    return View();
                }
            }
            else
            {
                if (search != null)
                {
                    var take = z.ShowItem;
                    var x = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.name.Contains(search) || i.status.Contains(search) && i.status=="unprocessed") select i;
                    var k = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.name.Contains(search) || i.status.Contains(search) && i.status=="psychotest") select i;
                    var l = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.name.Contains(search) || i.status.Contains(search) && i.status=="interview") select i;
                    var get = from a in x.Skip(take*(z.CurrentPage-1)).Take(take) select a;
                    var get1 = from a in k.Skip(take*(z.CurrentPage-1)).Take(take) select a;
                    var get2 = from a in l.Skip(take*(z.CurrentPage-1)).Take(take) select a;
                    ViewBag.emp = get;
                    ViewBag.emp1 = get1;
                    ViewBag.emp2 = get2;
                    ViewBag.page = z;
                    return View();
                }
                else
                {
                    var take = z.ShowItem;
                    var x = (from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.status == "unprocessed") select i).Skip(take*(z.CurrentPage-1)).Take(take);
                    var k = (from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.status == "psychotest") select i).Skip(take*(z.CurrentPage-1)).Take(take);
                    var l = (from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.status == "interview") select i).Skip(take*(z.CurrentPage-1)).Take(take);
                    ViewBag.emp = x;
                    ViewBag.emp1 = k;
                    ViewBag.emp2 = l;
                    ViewBag.page = z;
                    return View();
                }
            }
            }
            else
            {
            var y = (from i in _appdbcontext.leaves where i.status == "submitted" select i).Count();
            ViewBag.count = y;
            var z = _appdbcontext.pagings.Find(1);
            z.CurrentPage = _crntpage;
            _appdbcontext.SaveChanges();
            if (z.CurrentPage == 1)
            {
                if (search != null)
                {
                    var take = z.ShowItem;
                    var x = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.name.Contains(search) || i.status.Contains(search) && i.status=="unprocessed") select i;
                    var k = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.name.Contains(search) || i.status.Contains(search) && i.status=="psychotest") select i;
                    var l = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.name.Contains(search) || i.status.Contains(search) && i.status=="interview") select i;
                    var get = from a in x.Take(take) select a;
                    var get1 = from a in k.Take(take) select a;
                    var get2 = from a in l.Take(take) select a;
                    ViewBag.emp = get;
                    ViewBag.emp1 = get1;
                    ViewBag.emp2 = get2;
                    ViewBag.page = z;
                    return View();
                }
                else
                {
                    var take = z.ShowItem;
                    var x = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.status == "unprocessed") select i;
                    var k = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.status == "psychotest") select i;
                    var l = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.status == "interview") select i;
                    var get = from a in x.Take(take) select a;
                    var get1 = from a in k.Take(take) select a;
                    var get2 = from a in l.Take(take) select a;
                    ViewBag.emp = get;
                    ViewBag.emp1 = get1;
                    ViewBag.emp2 = get2;
                    ViewBag.page = z;
                    return View();
                }
            }
            else
            {
                if (search != null)
                {
                    var take = z.ShowItem;
                    var x = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.name.Contains(search) || i.status.Contains(search) && i.status=="unprocessed") select i;
                    var k = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.name.Contains(search) || i.status.Contains(search) && i.status=="psychotest") select i;
                    var l = from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.name.Contains(search) || i.status.Contains(search) && i.status=="interview") select i;
                    var get = from a in x.Skip(take*(z.CurrentPage-1)).Take(take) select a;
                    var get1 = from a in k.Skip(take*(z.CurrentPage-1)).Take(take) select a;
                    var get2 = from a in l.Skip(take*(z.CurrentPage-1)).Take(take) select a;
                    ViewBag.emp = get;
                    ViewBag.emp1 = get1;
                    ViewBag.emp2 = get2;
                    ViewBag.page = z;
                    return View();
                }
                else
                {
                    var take = z.ShowItem;
                    var x = (from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.status == "unprocessed") select i).Skip(take*(z.CurrentPage-1)).Take(take);
                    var k = (from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.status == "psychotest") select i).Skip(take*(z.CurrentPage-1)).Take(take);
                    var l = (from i in _appdbcontext.applicants.OrderByDescending(a => a.apply) where (i.status == "interview") select i).Skip(take*(z.CurrentPage-1)).Take(take);
                    ViewBag.emp = x;
                    ViewBag.emp1 = k;
                    ViewBag.emp2 = l;
                    ViewBag.page = z;
                    return View();
                }
            }
            }
        }

        [Authorize]

Downloads/FinalProject-1.1.0/FinalProject-1.0.0/Views/Applicant/Data.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
  .upload-btn-wrapper {
  position: relative;
  overflow: hidden;
  display: inline-block;
}

.btnx {
  border: 2px solid gray;
  color: gray;
  background-color: white;
  padding: 8px 20px;
  border-radius: 8px;
  font-size: 10px;
  font-weight: bold;
}

.upload-btn-wrapper input[type=file] {
  font-size: 20px;
  position: absolute;
  left: 0;
  top: 0;
  opacity: 0;
}
</style>

<!DOCTYPE html>
<html>
<title></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="text-center">
        <h2><b>Employee Information Form</b></h2>
        <p>Be Careful with Sensitive Data Information and Privacy</p>
      </div>
    </div>
  </div>
</div>
<br>

<div class="w3-sidebar w3-bar-block w3-black w3-card" style="width:130px; height: 275px">
  <h5 class="w3-bar-item">Biodata</h5>
  <button class="w3-bar-item w3-button tablink" onclick="openLink(event, 'Fade')">Profile</button>
</div>

<form method="POST" enctype="multipart/form-data">
<div class="container">
  <div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-6">
    <button asp-action="Add" asp-controller="Applicant" class="btn btn-success">Save</button>
    <button asp-action="AddNew" asp-controller="Applicant" class="btn btn-success">Save & Add New</button>
    <button type="button" class="btn btn-primary" onclick="window.location.href ='/Applicant'">Cancel</button>
    </div>
  </div>
</div>
<br>
<br>

<div style="margin-left:170px">
  <div class="w3-padding"><b>Fill this form completely and correct</b></div>

  <div id="Fade" class="w3-container city w3-animate-left" style="display:none">
    <h2>Profile</h2>
    <div class="row">
      <div class="col">
        <div id="1">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <img src="/images/paper.svg" style="width: 120px; height: 150px;">
        </div>
        <canvas style="width: 250px; height: 300px" id="pdfViewer"></canvas>
      </div>
      <div class="col">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <img id="imgPreview" alt="Preview Image" src="/images/img.svg" style="width: 120px; height: 180px;">
      </div>
    </div>
    <br>
    
    <div class="row">
    <div class="col">
    <div class="upload-btn-wrapper">
    <button class="btnx">Upload your CV</button>
    <input type="file" id="myPdf" name="cv">
    </div>
    </div>
    <div class="col">
    <div class="upload-btn-wrapper">
    <button class="btnx">Upload your Photo</button>
    <input type="file" name="photo" id="photo" onchange="showImagePreview(this)">
    </div>
    </div>
    </div>
    </div>
    <br>
    <br>

    <div class="row">
      <div class="col">
        <label>Full Name</label>
        <input class="form-control" placeholder="Name" id="name" name="name" required>
      </div>
      <div class="col">
        <label>Email</label>
        <input class="form-control" placeholder="Email" id="email" name="email" required>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col">
        <label>Phone Number</label>
        <input class="form-control" placeholder="Phone" id="phone" name="phone" required>
      </div>
      <div class="col">
        <br>
        <label>Gender</label>
        <br>
        <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="gender" id="gender1" value="Male">
        <label class="form-check-label" for="gender1">Male</label>
        </div>
        <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="gender" id="gender2" value="Female">
        <label class="form-check-label" for="gender2">Female</label>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col">
        <label>Bhirtdate</label>
        <input class="form-control" type="date" placeholder="date" id="date" name="date" required>
      </div>
      <div class="col">
        <label>Bhirtplace</label>
        <input class="form-control" placeholder="Place" id="place" name="place" required>
      </div>
    </div>
    <div class="row">
        <div class="col">
        <br>
        <label>Address</label>
        <input class="form-control" placeholder="Address" id="address" name="address" required>
        </div>
        <div class="col">
        <br>
        <label>Position</label>
        <input class="form-control" placeholder="Position" id="posisi" name="posisi" required>
        </div>
    </div>
  </div>
</div>
<br>
</form>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>


<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.2.js"></script>
  <script type="text/javascript">
  function showImagePreview(input) {
  if (input.files && input.files[0]) {
  var filerdr = new FileReader();
  filerdr.onload = function (e) {
  $('#imgPreview').attr('src', e.target.result);
  }
  filerdr.readAsDataURL(input.files[0]);
  }
  }
</script>

<script>
function openLink(evt, animName) {
  var i, x, tablinks;
  x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < x.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" w3-red", "");
  }
  document.getElementById(animName).style.display = "block";
  evt.currentTarget.className += " w3-red";
}
</script>
   
<script>
  // Loaded via <script> tag, create shortcut to access PDF.js exports.
var pdfjsLib = window['pdfjs-dist/build/pdf'];
// The workerSrc property shall be specified.
pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://mozilla.github.io/pdf.js/build/pdf.worker.js';

$("#myPdf").on("change", function(e){
  $("#1").remove();
	var file = e.target.files[0]
	if(file.type == "application/pdf"){
		var fileReader = new FileReader();  
		fileReader.onload = function() {
			var pdfData = new Uint8Array(this.result);
			// Using DocumentInitParameters object to load binary data.
			var loadingTask = pdfjsLib.getDocument({data: pdfData});
			loadingTask.promise.then(function(pdf) {
			  console.log('PDF loaded');
			  
			  // Fetch the first page
			  var pageNumber = 1;
			  pdf.getPage(pageNumber).then(function(page) {
				console.log('Page loaded');
				
				var scale = 1.5;
				var viewport = page.getViewport({scale: scale});

				// Prepare canvas using PDF page dimensions
				var canvas = $("#pdfViewer")[0];
				var context = canvas.getContext('2d');
				canvas.height = viewport.height;
				canvas.width = viewport.width;

				// Render PDF page into canvas context
				var renderContext = {
				  canvasContext: context,
				  viewport: viewport
				};
				var renderTask = page.render(renderContext);
				renderTask.promise.then(function () {
				  console.log('Page rendered');
				});
			  });
			}, function (reason) {
			  // PDF loading error
			  console.error(reason);
			});
		};
		fileReader.readAsArrayBuffer(file);
	}
});
</script>
</body>
</html> 

Downloads/FinalProject-1.1.0/FinalProject-1.0.0/Views/Applicant/Edit.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
  .upload-btn-wrapper {
  position: relative;
  overflow: hidden;
  display: inline-block;
}

.btnx {
  border: 2px solid gray;
  color: gray;
  background-color: white;
  padding: 8px 20px;
  border-radius: 8px;
  font-size: 10px;
  font-weight: bold;
}

.upload-btn-wrapper input[type=file] {
  font-size: 20px;
  position: absolute;
  left: 0;
  top: 0;
  opacity: 0;
}
</style>

<!DOCTYPE html>
<html>
<title></title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<body>

<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="text-center">
        <h2><b>Employee Information Form</b></h2>
        <p>Be Careful with Sensitive Data Information and Privacy</p>
      </div>
    </div>
  </div>
</div>
<br>

<div class="w3-sidebar w3-bar-block w3-black w3-card" style="width:130px; height: 275px">
  <h5 class="w3-bar-item">Biodata</h5>
  <button class="w3-bar-item w3-button tablink" onclick="openLink(event, 'Fade')">Profile</button>
</div>

@{
    var x = ViewBag.app;
    foreach (var i in x)
    {


<form method="POST" enctype="multipart/form-data">
<div class="container">
      <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-6">
              <button asp-action="Editor" asp-controller="Applicant" class="btn btn-success">Save</button>
              <button type="button" class="btn btn-primary" onclick="window.location.href ='/Applicant'">Cancel</button>
          </div>
      </div>
  </div>
  <br>
<div style="margin-left:170px">
  <div class="w3-padding"><b>Fill this form completely and correct</b></div>

  <div id="Fade" class="w3-container city w3-animate-left" style="display:none">
    <h2>Profile</h2>
    <div class="row">
      <div class="col">
        <div id="1">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <img src="/images/paper.svg" style="width: 120px; height: 150px;">
        </div>
        <canvas style="width: 250px; height: 300px" id="pdfViewer"></canvas>
      </div>
      <div class="col">
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <img id="imgPreview" alt="Preview Image" src="@i.photo" style="width: 120px; height: 180px;">
      </div>
    </div>
    <br>
    
    <div class="row">
    <div class="col">
    <div class="upload-btn-wrapper">
    <button class="btnx">Upload your CV</button>
    <input type="file" id="myPdf" src="@i.cv" name="cv">
    </div>
    </div>
    <div class="col">
    <div class="upload-btn-wrapper">
    <button class="btnx">Upload your Photo</button>
    <input type="file" name="photo" id="photo" value="@i.photo" onchange="showImagePreview(this)">
    </div>
    </div>
    </div>
    </div>
    <br>
    <br>

    <div class="row">
      <div class="col">
        <h3><b>STATUS: @i.status</b></h3>
      </div>
    </div>
    <br>
    
    <div class="row">
      <div class="col">
        <label>Full Name</label>
        <input id="id" name="id" value="@i.id" hidden>
        <input class="form-control" placeholder="Name" id="name" name="name" value="@i.name" required>
      </div>
      <div class="col">
        <label>Email</label>
        <input class="form-control" placeholder="Email" id="email" name="email" value="@i.email" required>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col">
        <label>Phone Number</label>
        <input class="form-control" placeholder="Phone" id="phone" name="phone" value="@i.phone" required>
      </div>
      <div class="col">
        <br>
        <label>Gender</label>
        <br>
        <div class="form-check form-check-inline">
        <input id="2" value="@i.gender" hidden>
        <input class="form-check-input" type="radio" name="gender" id="gender1" value="Male" required>
        <label class="form-check-label" for="gender1">Male</label>
        </div>
        <div class="form-check form-check-inline">
        <input class="form-check-input" type="radio" name="gender" id="gender2" value="Female" required>
        <label class="form-check-label" for="gender2">Female</label>
        </div>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col">
        <label>Bhirtdate</label>
        <input id="4" value="@i.bhirtdate" hidden>
        <input class="form-control" type="date" placeholder="date" id="date" name="date" value="@i.bhirtdate" required>
      </div>
      <div class="col">
        <label>Bhirtplace</label>
        <input class="form-control" placeholder="Place" id="place" name="place" value="@i.bhirtplace" required>
      </div>
    </div>
    <div class="row">
        <div class="col">
        <br>
        <label>Address</label>
        <input class="form-control" placeholder="Address" id="address" name="address" value="@i.address" required>
        </div>
        <div class="col">
        <br>
        <label>Position</label>
        <input class="form-control" placeholder="Position" id="posisi" name="posisi" value="@i.posisi" required>
        </div>
    </div>
  </div>
<br>
</form>
    }
}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script> 
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>


<script type="text/javascript" src="http://code.jquery.com/jquery-1.8.2.js"></script>
  <script type="text/javascript">
  function showImagePreview(input) {
  if (input.files && input.files[0]) {
  var filerdr = new FileReader();
  filerdr.onload = function (e) {
  $('#imgPreview').attr('src', e.target.result);
  }
  filerdr.readAsDataURL(input.files[0]);
  }
  }
</script>

<script>
function openLink(evt, animName) {
  var i, x, tablinks;
  x = document.getElementsByClassName("city");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablink");
  for (i = 0; i < x.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" w3-red", "");
  }
  document.getElementById(animName).style.display = "block";
  evt.currentTarget.className += " w3-red";
}
</script>
   
<script>
  // Loaded via <script> tag, create shortcut to access PDF.js exports.
var pdfjsLib = window['pdfjs-dist/build/pdf'];
// The workerSrc property shall be specified.
pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://mozilla.github.io/pdf.js/build/pdf.worker.js';

$("#myPdf").on("change", function(e){
  $("#1").remove();
	var file = e.target.files[0]
	if(file.type == "application/pdf"){
		var fileReader = new FileReader();  
		fileReader.onload = function() {
			var pdfData = new Uint8Array(this.result);
			// Using DocumentInitParameters object to load binary data.
			var loadingTask = pdfjsLib.getDocument({data: pdfData});
			loadingTask.promise.then(function(pdf) {
			  console.log('PDF loaded');
			  
			  // Fetch the first page
			  var pageNumber = 1;
			  pdf.getPage(pageNumber).then(function(page) {
				console.log('Page loaded');
				
				var scale = 1.5;
				var viewport = page.getViewport({scale: scale});

				// Prepare canvas using PDF page dimensions
				var canvas = $("#pdfViewer")[0];
				var context = canvas.getContext('2d');
				canvas.height = viewport.height;
				canvas.width = viewport.width;

				// Render PDF page into canvas context
				var renderContext = {
				  canvasContext: context,
				  viewport: viewport
				};
				var renderTask = page.render(renderContext);
				renderTask.promise.then(function () {
				  console.log('Page rendered');
				});
			  });
			}, function (reason) {
			  // PDF loading error
			  console.error(reason);
			});
		};
		fileReader.readAsArrayBuffer(file);
	}
});
</script>

<script type="text/javascript">
var date = document.getElementById("4").value;
spliter = date.split("/");
year = spliter[2].substring(0,4);
month = spliter[0];
day = spliter[1];
var bhirtdate;
if (month.length<2)
{
  if (day.length<2)
  {
    bhirtdate = year+"-0"+month+"-0"+day;
    bhirtdate = bhirtdate.toString();
  }
  else
  {
    bhirtdate = year+"-0"+month+"-"+day;
    bhirtdate = bhirtdate.toString();
  }
}
else
{
  if(day.length<2)
  {
    bhirtdate = year+"-"+month+"-0"+day;
    bhirtdate = bhirtdate.toString();
  }
  else
  {
    bhirtdate = year+"-"+month+"-"+day;
    bhirtdate = bhirtdate.toString();
  }
}
console.log(bhirtdate);
document.getElementById("date").value = bhirtdate;
</script>

<script type="text/javascript">
var gender = document.getElementById("2").value;
if (gender == "Male")
{
  radiobtn = document.getElementById("gender1");
  radiobtn.checked = true;
}
else if (gender == "Female")
{
  radiobtn = document.getElementById("gender2");
  radiobtn.checked = true;
}
</script>

<script type="text/javascript">
var date = document.getElementById("3").value;
spliter = date.split("/");
year = spliter[2].substring(0,4);
month = spliter[0];
day = spliter[1];
var bhirtdate;
if (month.length<2)
{
  if (day.length<2)
  {
    dates = year+"-0"+month+"-0"+day;
    dates = dates.toString();
  }
  else
  {
    dates = year+"-0"+month+"-"+day;
    dates = dates.toString();
  }
}
else
{
  if(day.length<2)
  {
    dates = year+"-"+month+"-0"+day;
    dates = dates.toString();
  }
  else
  {
    dates = year+"-"+month+"-"+day;
    dates = dates.toString();
  }
}
document.getElementById("apply").value = dates;
</script>

</body>
</html> 